### ISSUE TITLE
Focal length

### ISSUE THREAD

**Issue by Allanohanergo** [technocranes/technocrane-unreal#1]
Hi

The values in  "focal length min" and "focal length max" does not correspond with the "present focal length" - meaning if I set the zoom on say 75% on NT22 on a lens that is from 4,3 to 60 - is it possible to use the zoom table from the NT22 in some way ?

**Comment by Neill3d** [comment]
Do you stream calibrated zoom data from a technocrane desk ?

**Comment by Allanohanergo** [comment]
I stream from a NT22 with a digital lens output - the data seems to come out in % - from 0-100 - but it should be possible to get the "real" FoV number from the lens ?

**Comment by Neill3d** [comment]
yes, there is a way to do a lens calibration in technocrane, that mostly a question not for me, as I didn't work too much with a hardware, but when we did tests, there was two possibilities - manual output and calibrated real value output. When you are sending percentage from 0 to 100, that means manual calibration, it's not a preferable way, but in that case you can tweak your values by adapting into a range defined by these properties https://github.com/technocranes/technocrane-unreal/blob/11999b9c2bcc97c6641d80b280619ce1bff0feda/Source/TechnocranePlugin/Public/TechnocraneCamera.h#L67
As for clamps on 60, not sure why that happen, I'll check

**Comment by Allanohanergo** [comment]
I simply did not disable "only raw output" in data export settings in the desk software .....
It only works when OK is pressed ;-)

**Comment by Neill3d** [comment]
That's nice, I think we can close the topic.

**Comment by Allanohanergo** [comment]
Dear Sergei

Plugin working in 4.20.3 - we can now transform the base but would like to get reading on the position AFTER transform 

Also - will the plugin work in future versions of UE without any work or how does it work ? 

Thx

Allan O Lückow
+ 45 20114488
