### ISSUE TITLE
CGI/FBX converter arguments for TechnoDolly FBX import

### ISSUE THREAD

**Issue by Allanohanergo** [technocranes/technocrane-unreal#2]
Hi 

What is the correct arguments for conversion of a random FBX file to a FBX file that can work for import in TD sw ?

Allan

**Comment by markpatty** [comment]
Hi, did you ever answer this problem? I'm currently having the same issue. It appears that the command isn't noted in the help on how to access the FBX eEULER conversion. 

Mark

**Comment by Allanohanergo** [comment]
No I didnt 

But I started to export in 2011 and it all works fine when importing

Allan

**Comment by markpatty** [comment]
Thanks so much for the quick reply. 

In Maya 2011 or do you just use the Maya 2011 option in FBX export settings? I'm doing the latter and the axis appears to be the wrong way around and crashes the desk. I was told by the Techno guys that it needs to be Y-up, yet the Techno is Z-up.

Many thanks again

Mark

**Comment by Allanohanergo** [comment]
Just the option

And I believe you need to rotate so its in the correct XYZ order

Sorry can t remember exactly what the Techviz people do but I can ask them when Im on set tomorrow

Try the different ones maybe ?

Allan

**Comment by markpatty** [comment]
Thank you Allan, I'll try those options but if you don't mind asking tomorrow I'd be very grateful. I'll let you know if I figure it out this end. 

Kind regards

Mark

**Comment by Allanohanergo** [comment]
Hi

I just talked to Sergei who make the plugin etc

And he says 

eEULER_ZXY

Hope that helps

Allan

**Comment by markpatty** [comment]
Hi Allan,

Thank you, unfortunately it's converting to eEULER_ZXY from the default eEULER_XYZ that's the problem. I was hoping the CGI_Conv tool would do it but the command seems to be missing in the write up on the Github page. I'm emailing Sergei now to see if he knows how to use it for this purpose. Fingers crossed....

Mark

**Comment by Allanohanergo** [comment]
When you rotate to ZXY in Maya and export 2011 it should work

Not sure what you mean by 
“Its converting to XY from default”

**Comment by markpatty** [comment]
Hi Allan,

I have managed to get this successfully working now, thank you for your help. I think the CGI-Conv software was a red hearing as it worked by ensuring the camera rotation order was set to ZXY before exporting. Simple when you know how. 

Thanks again for the help and quick replies, I really appreciate it

Mark
