### ISSUE TITLE
Why could i not receviced UDP data

### ISSUE THREAD

**Issue by KapoYU** [technocranes/technocrane-unreal#4]

**Comment by Allanohanergo** [comment]
Hi - I am using UDP data from TechnoCrane every day - what is the problem ?

**Comment by KapoYU** [comment]
UDP can be received from other live link plug-in. This plug-in can't receive it. It's always waiting status. The UDP address is correct. What's wrong with my operation

**Comment by Allanohanergo** [comment]
What is sending ? A TechnoCrane with what version software ?

**Comment by KapoYU** [comment]
The TechnoCrane version is 1,4.0,The UE4 version is 4.25.I've turned off all UDP usage except this one,the log is aways missed sync

**Comment by Allanohanergo** [comment]
Can you see data in the datadisplay application ?

Allan O Luckow

TechnoDolly Operator

AUS + 61 466 631 917
aluckow@mcustudios.com

DK +45 20114488
allanluckow@me.com

**Comment by KapoYU** [comment]
I can't see any connected devices

**Comment by Allanohanergo** [comment]
Start with getting data running in datadisplay - its not Unreal 

Then you are sure data is flowing from crane

Datadisplay is on GitHub 

Allan O Luckow

TechnoDolly Operator

AUS + 61 466 631 917
aluckow@mcustudios.com

DK +45 20114488
allanluckow@me.com

**Comment by KapoYU** [comment]
I've opened UDP to send data. Other plug-ins can get data, but ours can't

**Comment by Allanohanergo** [comment]
Not sure I understand 

Do you see data from Crane somewhere else but not in UE ?




Allan O Luckow

TechnoDolly Operator

AUS + 61 466 631 917
aluckow@mcustudios.com

DK +45 20114488
allanluckow@me.com

**Comment by Neill3d** [comment]
Try please to connect with data display at first without running ue4 as Allan mentioned. Here you can find windows binaries - https://github.com/technocranes/technocrane-tools/releases

**Comment by Neill3d** [comment]
btw, are you running under the local network ?

**Comment by KapoYU** [comment]
I get the real camera data, then send it to the local computer through UDP, and finally enter UE4.

**Comment by KapoYU** [comment]
Our testing tool technocrane- tools.exe The file cannot be opened in Windows 10.

**Comment by KapoYU** [comment]
UDP data has been sent and can be monitored

**Comment by Allanohanergo** [comment]
What is “real camera data” ?

How is the crane connected ?

To a switch or directly to pc ? 

run datadisplay and take a screendump of the running streaming data 

Vh

Allan O Lückow
+ 45 20114488
